[10.0] [IMP] l10n nl partner salutation gender
OCA/l10n-netherlands pull request #120
Opened 2017-10-05 11:46 UTC by NL66278

- Resolve incompatibilities with partner_contact_gender.
- Improved handling of company partners.
- Improved OCA standard compliance.
- Improved tests.
- Recognize difference between unknown gender (will be False/NULL) and other.

2017-10-05 13:23 UTC, NL66278 commented
Runbot errors are due to problems with runbot - as usual

2017-10-05 13:31 UTC, hbrunn requested changes

2017-10-05 13:31 UTC, hbrunn commented on l10n_nl_partner_salutation/models/res_partner.py
> +        'male': 'De heer',
what i disliked with the 8 version is that we'll never be able to address non dutch speaking people with the dutch regime. Better put this in a function of its own to return the dictionary, then you can wrap the values in `_()`. And you also enable other modules to hook in there and do what they think is the good default.

2017-10-05 13:31 UTC, hbrunn commented on l10n_nl_partner_salutation/models/res_partner.py
> +            name_format="${firstname or initials or ''}"
the idea for having `get_salutation_name_format` in its own function was modularity, so other modules can change that format as they please. Any reason to destroy this possibility?

2017-12-11 12:27 UTC, hbrunn commented
@NL66278 can you fix [travis](https://travis-ci.org/OCA/l10n-netherlands/jobs/285796831)? then we'll be able to merge this

2017-12-11 14:18 UTC, hbrunn approved these changes

2018-01-16 15:34 UTC, merged