[ADD] Add company types data module
OCA/l10n-netherlands pull request #144
Opened 2018-01-18 13:48 UTC by lfreeke

Add company types data. Depends on partner_company_type module.

2018-01-18 13:48 UTC, lfreeke commented
@NL66278 ping

2018-01-19 10:33 UTC, NL66278 commented on l10n_nl_company_type/__manifest__.py
> +# Copyright 2018 Therp BV <http://therp.nl>
https everywhere (actually can also be done for License, but do not know wether that is according to oca standards)

2018-01-19 10:33 UTC, NL66278 commented on l10n_nl_company_type/__manifest__.py
> +    "summary": "",
Please add a summary

2018-01-24 12:06 UTC, NL66278 approved these changes
LGTM and test

2018-02-01 09:37 UTC, hbrunn requested changes

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/README.rst
> +l10n_nl_company_type
use a human readable name

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/README.rst
> +The module depens on partner_company_type
depenDs

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/README.rst
> +.. repo_id is available in https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt
resolve repo_id

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/README.rst
> +* ...
remove empty section

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/__manifest__.py
> +    "name": "l10n_nl_company_type",
friendly name

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/data/l10n_nl_company_types.xml
> +            <field name="name">Stichting</field>
this is a translatable field, so add the data in English and add a translation file

2018-02-01 09:37 UTC, hbrunn commented on l10n_nl_company_type/data/l10n_nl_company_types.xml
> +            <field name="shortcut">ez</field>
same here

2018-02-02 11:43 UTC, lfreeke commented
@hbrunn fixed

2018-02-02 12:12 UTC, NL66278 commented on l10n_nl_dutch_company_type/data/l10n_nl_dutch_company_types.xml
> +<?xml version="1.0" encoding="UTF-8"?>
You have the same file twice, one with plural one with singular name. Use git rm

2018-02-02 14:13 UTC, hbrunn approved these changes

2018-02-02 14:13 UTC, merged