[10.0] [ADD] letsencrypt_transip_nl
OCA/l10n-netherlands pull request #259
Opened 2020-04-16 14:49 UTC by janverb

This is a continuation of #179. It depends on OCA/server-tools#1813.

Add a module for doing Let's Encrypt validation with TransIP's DNS service.

2020-04-22 12:42 UTC, hbrunn requested changes

2020-04-22 12:42 UTC, hbrunn commented on oca_dependencies.txt
> +server-tools https://github.com/janverb/server-tools.git 10.0-use-acme-client
I'll keep this as reminder that we can't merge before our dependency is merged and this changed

2021-08-22 18:57 UTC, NL66278 approved these changes
:+1: LGTM

2022-02-18 17:06 UTC, NL66278 commented
Replaced by this one: squashed the fixup commits and no longer changes oca dependencies:

https://github.com/OCA/l10n-netherlands/pull/341

2022-02-22 21:25 UTC, closed without merging