[ADD] #8004 add l10n_nl_dutch_company_type
OCA/l10n-netherlands pull request #279
Opened 2020-10-08 16:02 UTC by gfcapalbo

Migrating

2020-10-15 08:20 UTC, lfreeke commented on l10n_nl_dutch_company_type/data/l10n_nl_dutch_company_type.xml
> +    <record
Make sure the country_id is set.

2020-10-15 08:49 UTC, NL66278 commented
@gfcapalbo Please use the official procedure for migrating modules, preserving history.

2020-12-11 14:15 UTC, NL66278 commented
@gfcapalbo Will you take up the request to follow the official migration method?

2021-02-28 12:09 UTC, bosd requested changes
Please add a ```USAGE.RST```

```
To use this module, you need to:

* Open a form of a contact and set it as *Company* (not a *Individual*)
* select the appropriate legal form```

2021-02-28 12:09 UTC, bosd commented on l10n_nl_dutch_company_type/data/l10n_nl_dutch_company_type.xml
> +    <record
Since the laws applicable to an Dutch Limited are different then an Limited company in a different EU jurisdiction. I don't see the use case of possible combining them.

as such a ```bv``` is specific for nl. The ```<field name="name">Besloten vennootschap met gewone structuur</field>```
indicate that these are legal forms of the netherlands by including the country in the record.
```<field name="country" ref="base.nl"/>```
for legal forms the following data source can be used: https://developers.kvk.nl/images/KVK_APIs_Manual_test_v1.2.pdf
page 11

2021-02-28 12:09 UTC, bosd commented on l10n_nl_dutch_company_type/__manifest__.py
> +    "category": "Dutch localization",
Consistency improvement for odoo appstore and backend apps list
```"category": "Localization",```

2021-02-28 12:10 UTC, bosd commented
Interesting module.

Is it compatible with the data fetched from the kvk with these modules:
l10n_nl_kvk
l10n_nl_openkvk
https://developers.kvk.nl/documentation

2021-02-28 12:42 UTC, bosd commented
Oops, my comments about data source are maybe better suited for an improvement PR instead of standard migration :smile:

2021-09-27 08:00 UTC, NL66278 commented
Based on the work by @gfcapalbo and the comments of @bosd I created a new PR with the official migration method preserving history here: https://github.com/OCA/l10n-netherlands/pull/336

2021-09-27 08:00 UTC, closed without merging