13.0 l10n nl mis reports
OCA/l10n-netherlands pull request #327
Opened 2021-06-29 12:01 UTC by gfcapalbo

Trivial porting of I10n_nl_mis_reports to v13. version change and removed deprecated multi decorator. 

Methodology:
by diffing mis_builder v12 and v13 we can see no changes have been made in  the templates mis_builder.report_mis_report_instance or qweb MisReportWidgetTemplate.
These are the only two used by this reporting.
Also we have verified that all account data  referenced in /data  is still existing and has the same function as it did in 12.

Because all this is unvaried, it is possible to install and port this with the minimal changes in this MR.
Tested on client server.
Reported a small (CSS?) oddity , visible exclusively in Firefox, added to README/Known Issues.

2021-06-29 12:03 UTC, gjotten commented
LGTM functionally on client server.

2021-06-29 12:06 UTC, gjotten approved these changes

2021-06-29 12:29 UTC, gfcapalbo commented
failing on 
2021-06-29 12:19:21,893 5952 INFO openerp_test odoo.addons.l10n_nl_tax_invoice_basis.tests.test_tax_invoice_basis: ======================================================================

2021-06-29 12:19:21,893 5952 ERROR openerp_test odoo.addons.l10n_nl_tax_invoice_basis.tests.test_tax_invoice_basis: ERROR: TestTaxInvoiceBasis.test_02_tax_standard

but i see no relation between this code and the failed test on l10n_nl_tax_invoice_basis. I see main branch failing. 
any help is welcome.

2021-06-29 13:00 UTC, thomaspaulb requested changes
nitpicks only

2021-06-29 13:00 UTC, thomaspaulb commented on l10n_nl_mis_reports/README.rst
> +* support horizontal mode for xslx export
xlsx

2021-06-29 13:00 UTC, thomaspaulb commented on l10n_nl_mis_reports/README.rst
> +* Holger Brunn <mail@hunki-enterprises.nl> (https://hunki-enterprises.nl)
Giovanni

2021-06-29 13:00 UTC, thomaspaulb commented on l10n_nl_mis_reports/__manifest__.py
> +    "version": "13.0.1.1.0",
13.0.1.0.0

2021-06-30 05:09 UTC, hbrunn requested changes
please keep original commits according to the [migration howto](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0#howto) and squash the migration commits

2021-11-12 06:41 UTC, closed without merging