17.0 mig l10n nl xaf auditfile export
OCA/l10n-netherlands pull request #416
Opened 2024-03-25 15:40 UTC by Wodran14

2024-03-25 15:51 UTC, hbrunn requested changes
please fix tests.

And you'll very much want to review/include https://github.com/OCA/l10n-netherlands/pull/413 in your migration

2024-03-26 10:53 UTC, Wodran14 commented
@hbrunn Review pls.

2024-04-01 07:56 UTC, hbrunn approved these changes

2024-04-04 10:56 UTC, thomaspaulb approved these changes

2024-04-04 10:57 UTC, thomaspaulb commented
/ocabot migration l10n_nl_xaf_auditfile_export

/ocabot merge nobump

2024-04-04 11:02 UTC, merged