Missing Dutch Translations
OCA/l10n-netherlands pull request #99
Opened 2017-07-22 10:20 UTC by ploegvde

2017-07-22 12:01 UTC, hbrunn requested changes
￼￼the postcodeapi translation conflicts, please rebase

2017-07-22 12:01 UTC, hbrunn commented on l10n_nl_intrastat/i18n/nl.po
> +msgstr "<span>Afgedruk: </span>"
't' missing?

2017-07-24 08:04 UTC, hbrunn approved these changes

2017-07-25 07:15 UTC, CasVissers-360ERP approved these changes

2017-07-25 14:25 UTC, merged